# Generated by Django 4.1.5 on 2023-03-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(db_index=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(db_index=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.IntegerField(null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_fa',
            field=models.IntegerField(null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_fa',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
    ]
