# Generated by Django 4.1.5 on 2023-03-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_product_description_en_product_description_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productbrand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_fa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productbrand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ManyToManyField(null=True, related_name='product_categories', to='product_module.productcategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_fa',
            field=models.ManyToManyField(null=True, related_name='product_categories', to='product_module.productcategory', verbose_name='category'),
        ),
    ]
