# Generated by Django 4.1.5 on 2023-03-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_remove_product_price_en_remove_product_price_fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_fa',
        ),
        migrations.AddField(
            model_name='productbrand',
            name='title_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='title'),
        ),
    ]
