# Generated by Django 4.1.5 on 2023-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='site name')),
                ('site_url', models.CharField(max_length=200, verbose_name='site url')),
                ('address', models.CharField(max_length=200, verbose_name='site address')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='phone')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='fax')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='email')),
                ('copyright', models.TextField(verbose_name='copyright')),
                ('about_us_text', models.TextField(verbose_name='a bout us')),
                ('site_logo', models.ImageField(upload_to='', verbose_name='logo')),
                ('is_main_setting', models.BooleanField(verbose_name='main setting')),
            ],
            options={
                'verbose_name': 'site setting',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
