# Generated by Django 4.1.5 on 2023-02-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_footerlinkbox_alter_sitesetting_address_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('url', models.URLField(verbose_name='url')),
                ('url_title', models.CharField(max_length=200, verbose_name='url title')),
                ('image', models.ImageField(upload_to='images/sliders', verbose_name='image')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
            },
        ),
    ]
