# Generated by Django 4.1.5 on 2023-03-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_sitebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
