# Generated by Django 4.1.5 on 2023-03-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_slider_description_en_slider_description_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='url title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='url_title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='url title'),
        ),
    ]
