# Generated by Django 4.1.5 on 2023-03-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_slider_url_title_en_slider_url_title_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='footerlinkbox',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='footer link box'),
        ),
        migrations.AddField(
            model_name='footerlinkbox',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='footer link box'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_us_text_en',
            field=models.TextField(null=True, verbose_name='a bout us'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_us_text_fa',
            field=models.TextField(null=True, verbose_name='a bout us'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='copyright_en',
            field=models.TextField(null=True, verbose_name='copyright'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='copyright_fa',
            field=models.TextField(null=True, verbose_name='copyright'),
        ),
    ]
