# Generated by Django 4.1.5 on 2023-01-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, verbose_name='email')),
                ('full_name', models.CharField(max_length=300, verbose_name='full name ')),
                ('message', models.TextField(verbose_name='message')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('is_read_by_admin', models.BooleanField(verbose_name='is read by admin')),
                ('response', models.BooleanField(blank=True, null=True, verbose_name='response')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
            ],
            options={
                'verbose_name': 'contact us ',
                'verbose_name_plural': 'list contact us',
            },
        ),
    ]
