# Generated by Django 4.1.5 on 2023-01-22 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title of category')),
                ('url_title', models.CharField(max_length=200, unique=True, verbose_name='title in url ')),
                ('is_active', models.BooleanField(default=True, verbose_name='active/disable')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecategory', verbose_name='parent of category')),
            ],
            options={
                'verbose_name': 'article category',
                'verbose_name_plural': 'article categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title of article')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, verbose_name='title in url')),
                ('image', models.ImageField(upload_to='images/article', verbose_name='image of article')),
                ('short_description', models.TextField(verbose_name='short description')),
                ('text', models.TextField(verbose_name='text of article')),
                ('is_active', models.BooleanField(default=True, verbose_name='active/disable')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('selected_category', models.ManyToManyField(to='article_module.articlecategory', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
