# Generated by Django 4.1.5 on 2023-02-06 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date.today, verbose_name='create date'),
            preserve_default=False,
        ),
    ]
