# Generated by Django 4.1.5 on 2023-02-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'article comment', 'verbose_name_plural': 'article comments'},
        ),
    ]
