# Generated by Django 4.1.5 on 2023-03-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_alter_articlecomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bar',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
