# Generated by Django 4.1.5 on 2023-03-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_articlevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_fa',
            field=models.TextField(null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=models.TextField(null=True, verbose_name='text of article'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_fa',
            field=models.TextField(null=True, verbose_name='text of article'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='title of article'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='title of article'),
        ),
    ]
